import { Cafe, Visit, Wishlist } from './types';

// 假資料：咖啡廳清單
export const mockCafes: Cafe[] = [
  {
    id: 1,
    name: 'Cafe Nomad',
    description: '舒適的工作空間，提供優質咖啡和快速 WiFi',
    address: '台北市大安區復興南路一段 253 號',
    category: '辦公友善',
    rating: 4.5,
    priceLevel: 2,
    hasWifi: true,
    hasPowerOutlets: true,
    hasTimeLimit: false,
    isNoisy: false,
    hasGoodLighting: true,
    hasAvailableSeats: true,
    createdBy: 1,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'Coffee Stand',
    description: '明亮開闊的空間，適合長時間工作',
    address: '台北市中正區羅斯福路三段 283 巷 21 號',
    category: '辦公友善',
    rating: 4.3,
    priceLevel: 2,
    hasWifi: true,
    hasPowerOutlets: true,
    hasTimeLimit: false,
    isNoisy: false,
    hasGoodLighting: true,
    hasAvailableSeats: true,
    createdBy: 1,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 3,
    name: 'Fika Fika Cafe',
    description: '北歐風格咖啡廳，環境舒適安靜',
    address: '台北市中山區伊通街 33 號',
    category: '精品咖啡',
    rating: 4.6,
    priceLevel: 3,
    hasWifi: true,
    hasPowerOutlets: false,
    hasTimeLimit: true,
    isNoisy: false,
    hasGoodLighting: true,
    hasAvailableSeats: false,
    createdBy: 1,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 4,
    name: 'Rufous Coffee',
    description: '專業手沖咖啡，環境優雅',
    address: '台北市中山區民生東路三段 142 號',
    category: '精品咖啡',
    rating: 4.7,
    priceLevel: 3,
    hasWifi: true,
    hasPowerOutlets: true,
    hasTimeLimit: false,
    isNoisy: false,
    hasGoodLighting: true,
    hasAvailableSeats: true,
    createdBy: 1,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 5,
    name: 'Congrats Cafe',
    description: '時尚簡約風格，適合聚會和工作',
    address: '台北市信義區松仁路 90 號',
    category: '辦公友善',
    rating: 4.4,
    priceLevel: 2,
    hasWifi: true,
    hasPowerOutlets: true,
    hasTimeLimit: false,
    isNoisy: true,
    hasGoodLighting: true,
    hasAvailableSeats: true,
    createdBy: 1,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 6,
    name: 'Louisa Coffee',
    description: '連鎖咖啡品牌，環境整潔服務穩定',
    address: '台北市松山區南京東路四段 133 號',
    category: '連鎖品牌',
    rating: 4.1,
    priceLevel: 2,
    hasWifi: true,
    hasPowerOutlets: true,
    hasTimeLimit: false,
    isNoisy: true,
    hasGoodLighting: true,
    hasAvailableSeats: true,
    createdBy: 1,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-06T00:00:00Z',
  },
  {
    id: 7,
    name: 'Cafe Lugo',
    description: '日式風格咖啡廳，提供手沖咖啡',
    address: '台北市萬華區西門町成都路 10 號',
    category: '日式風格',
    rating: 4.4,
    priceLevel: 3,
    hasWifi: false,
    hasPowerOutlets: false,
    hasTimeLimit: true,
    isNoisy: false,
    hasGoodLighting: false,
    hasAvailableSeats: true,
    createdBy: 1,
    createdAt: '2025-01-07T00:00:00Z',
    updatedAt: '2025-01-07T00:00:00Z',
  },
  {
    id: 8,
    name: 'The Coffee Bean',
    description: '美式風格咖啡廳，空間寬敞舒適',
    address: '台北市士林區天母東路 69 號',
    category: '美式風格',
    rating: 4.2,
    priceLevel: 2,
    hasWifi: true,
    hasPowerOutlets: true,
    hasTimeLimit: false,
    isNoisy: true,
    hasGoodLighting: true,
    hasAvailableSeats: true,
    createdBy: 1,
    createdAt: '2025-01-08T00:00:00Z',
    updatedAt: '2025-01-08T00:00:00Z',
  },
];

// 假資料：到訪記錄
export const mockVisits: Visit[] = [
  {
    id: 1,
    cafeId: 1,
    userId: 1,
    visitDate: '2025-10-15',
    notes: '環境很好，咖啡也不錯',
    rating: 5,
    createdAt: '2025-10-15T10:00:00Z',
  },
  {
    id: 2,
    cafeId: 2,
    userId: 1,
    visitDate: '2025-10-18',
    notes: '空間寬敞，適合長時間待著',
    rating: 4,
    createdAt: '2025-10-18T14:30:00Z',
  },
];

// 假資料：願望清單
export const mockWishlist: Wishlist[] = [
  {
    id: 1,
    cafeId: 4,
    userId: 1,
    notes: '想去試試他們的手沖咖啡',
    createdAt: '2025-10-10T00:00:00Z',
  },
  {
    id: 2,
    cafeId: 5,
    userId: 1,
    notes: '朋友推薦的',
    createdAt: '2025-10-12T00:00:00Z',
  },
];

